export const deals = [
  {
    id: 1,
    name: "iPhone 17 Pro",
    price: 999,
    oldPrice: 1199,
    discount: 17,
    shop: "Apple Store",
    img: "📱",
    category: "Electronics",
  },
  {
    id: 2,
    name: "Sony WH-1000XM6",
    price: 299,
    oldPrice: 399,
    discount: 25,
    shop: "Sony Center",
    img: "🎧",
    category: "Audio",
  },
  {
    id: 3,
    name: "Mechanical Keyboard",
    price: 150,
    oldPrice: 200,
    discount: 20,
    shop: "Keychron",
    img: "⌨️",
    category: "Accessories",
  },
  {
    id: 4,
    name: "MacBook Air M4",
    price: 1099,
    oldPrice: 1299,
    discount: 15,
    shop: "Tiki Trading",
    img: "💻",
    category: "Computing",
  },
  {
    id: 5,
    name: "AirPods Pro 3",
    price: 199,
    oldPrice: 249,
    discount: 20,
    shop: "Amazon",
    img: "👂",
    category: "Audio",
  },
  {
    id: 6,
    name: "iPad Pro M4",
    price: 899,
    oldPrice: 999,
    discount: 10,
    shop: "Apple Store",
    img: "📟",
    category: "Electronics",
  },
];
