name = "dealy-scraper-service"
main = "scraper-worker.ts"
compatibility_date = "2024-01-01"

[triggers]
# Chạy mỗi 30 phút một lần
crons = ["*/30 * * * *"]

# Cấu hình để linkedom và pocketbase hoạt động trên Worker
[build]
command = "bun install"
